### ISSUE TITLE
checksum mismatch in travis with go 1.12.5

### ISSUE THREAD

**Issue by trtg** [hashicorp/go-rootcerts#9]
Running tests on travis and cannot build because of:

verifying github.com/hashicorp/go-rootcerts@v1.0.0: checksum mismatch
	downloaded: h1:Rqb66Oo1X/eSV1x66xbDccZjhJigjg0+e82kpwzSwCI=
	go.sum:     h1:ueI78wUjYExhCvMLow4icJnayNNFRgy0d9EGs/a1T44=

I'm using modules, I've tried go get -u github.com/hashicorp/go-rootcerts@v1.0.0 and I've tried pulling from a specific commit hash as suggested in an existing issue with:
go get github.com/hashicorp/go-rootcerts@6bb64b370b90e7ef1fa532be9e591a81c3493e00

None of that worked, had to just edit the go.sum to match what travis is downloading. Anyone know what could be going on here?

**Comment by trtg** [comment]
If anyone has any idea how to fix this, any help would be greatly appreciated. I see all the related threads being closed with no solution. This is an incredibly irritating issue, because every build re-inserts the go-rootcerts checksum back in the go.sum which then causes problems in travis. So every build I have to delete the new entries in go.sum

**Comment by jefferai** [comment]
It is the only tag. We're using this in a bunch of projects without any checksum issue. I really have no idea what the issue is.

**Comment by jefferai** [comment]
Are you only seeing this in Travis? If so can you verify that the version of Go being used is >= 1.12?

**Comment by thomloftus** [comment]
I'm using go 1.12.5 and having this same issue in Gitlab using the 1.0.0 tag...
if I update my go.sum with the checksum reported by this repo during a local build, it then fails to build in gitlab trying to build my project, claiming that this repos checksum is again different from the update I made locally - very confusing.

**Comment by jefferai** [comment]
What does `go mod verify` say?

If I get a fresh clone and verify it seems fine:

```
$ git clone https://github.com/hashicorp/go-rootcerts
Cloning into 'go-rootcerts'...
remote: Enumerating objects: 53, done.
remote: Total 53 (delta 0), reused 0 (delta 0), pack-reused 53
Unpacking objects: 100% (53/53), done.

$ cd go-rootcerts/

$ go mod verify
all modules verified
```

**Comment by jefferai** [comment]
Also I have updated the go.sum file to have (a) been created by go 1.12 and (b) use the updated version of go-homedir. I've pushed v1.0.1; see if this helps.

**Comment by thomloftus** [comment]
Thanks for trying.  I'm at a loss...

I've updated to the 1.0.1 tag but I get the same thing in Gitlab.
```
go: verifying github.com/hashicorp/go-rootcerts@v1.0.1: checksum mismatch
	downloaded: h1:eWJIsmmckW3INFytYnBIdzI+Vh7AgdrPVh2DBvwwCy0=
	go.sum:     h1:DMo4fmknnz0E0evoNYnV48RjWndOsmd6OW+09R3cEP8=
```

`go mod verify` in my repo appears to show what it should:

```
$ go mod verify
all modules verified
```
and my project go.sum shows the same checksum as what my CI is reporting in go.sum:
```
$ cat go.sum | grep rootcerts
github.com/hashicorp/go-rootcerts v1.0.1 h1:DMo4fmknnz0E0evoNYnV48RjWndOsmd6OW+09R3cEP8=
github.com/hashicorp/go-rootcerts v1.0.1/go.mod h1:pqUvnprVnM5bf7AOirdbb01K4ccR319Vf4pU3K5EGc8=
```

and a fresh copy of go-rootcerts@v1.0.1 appears to validate as well:
```
$ git clone https://github.com/hashicorp/go-rootcerts
Cloning into 'go-rootcerts'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 57 (delta 0), reused 3 (delta 0), pack-reused 53
Unpacking objects: 100% (57/57), done.
SFOLA2HFJG5J:workspace tloftus$ cd go-rootcerts/
SFOLA2HFJG5J:go-rootcerts tloftus$ go mod verify
all modules verified
```

It appears as if something in-between is altering the downloaded checksum for this repo, but I don't really understand how that would happen, and only in my CI environment, but not locally... 🤷‍♂

**Comment by thomloftus** [comment]
possible this is an issue with go modules itself and maybe not fully resolved...

https://stackoverflow.com/questions/54133789/go-modules-checksum-mismatch

**Comment by thomloftus** [comment]
apologies - further digging revealed that we were building in a gitlab container running an outdated version of Go.  A container running 1.12 fixed the issue for us.

**Comment by jefferai** [comment]
Awesome. Closing!

**Comment by trtg** [comment]
@jefferai This issue is not resolved for me- i can confirm that our travis containers, as noted in the title of this issue are running 1.12.5, the same version I'm running locally. I'm inclined to think @thomloftus first idea is correct in saying this might be an issue with go modules itself somehow computing different checksums on different platforms. Locally I run gentoo, our travis containers are based on ubuntu14.04 in the particular app I'm trying to fix.
